In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import PowerTransformer

from sklearn.model_selection import train_test_split ,GridSearchCV
from sklearn.linear_model import LinearRegression ,Lasso
from statsmodels.stats.outliers_influence import variance_inflation_factor
import statsmodels.api as sm
import warnings
warnings.filterwarnings('ignore')
from sklearn.tree import DecisionTreeRegressor, plot_tree
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import mean_squared_error , mean_absolute_error , r2_score

import pickle
import json

In [2]:
df=pd.read_csv('Dummy Data HSS-Marketing and Sales Data.csv')
df

        TV      Radio  Social Media Influencer       Sales
0     16.0   6.566231      2.907983       Mega   54.732757
1     13.0   9.237765      2.409567       Mega   46.677897
2     41.0  15.886446      2.913410       Mega  150.177829
3     83.0  30.020028      6.922304       Mega  298.246340
4     15.0   8.437408      1.405998      Micro   56.594181
...    ...        ...           ...        ...         ...
4567  26.0   4.472360      0.717090      Micro   94.685866
4568  71.0  20.610685      6.545573       Nano  249.101915
4569  44.0  19.800072      5.096192      Micro  163.631457
4570  71.0  17.534640      1.940873      Macro  253.610411
4571  42.0  15.966688      5.046548      Micro  148.202414

[4572 rows x 5 columns]

In [3]:
x = df.drop('Sales', axis = 1 )
y = df['Sales']
x

        TV      Radio  Social Media Influencer
0     16.0   6.566231      2.907983       Mega
1     13.0   9.237765      2.409567       Mega
2     41.0  15.886446      2.913410       Mega
3     83.0  30.020028      6.922304       Mega
4     15.0   8.437408      1.405998      Micro
...    ...        ...           ...        ...
4567  26.0   4.472360      0.717090      Micro
4568  71.0  20.610685      6.545573       Nano
4569  44.0  19.800072      5.096192      Micro
4570  71.0  17.534640      1.940873      Macro
4571  42.0  15.966688      5.046548      Micro

[4572 rows x 4 columns]

In [4]:
df.isnull().sum()

TV              10
Radio            4
Social Media     6
Influencer       0
Sales            6
dtype: int64

In [5]:
df.dropna(inplace=True)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4546 entries, 0 to 4571
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   TV            4546 non-null   float64
 1   Radio         4546 non-null   float64
 2   Social Media  4546 non-null   float64
 3   Influencer    4546 non-null   object
 4   Sales         4546 non-null   float64
dtypes: float64(4), object(1)
memory usage: 213.1+ KB

In [7]:
final_df = pd.get_dummies(df,dtype = int )
final_df

,TV,Radio,Social Media,Sales,Influencer_Macro,Influencer_Mega,Influencer_Micro,Influencer_Nano
0,16.0,6.566231,2.907983,54.732757,0,1,0,0
1,13.0,9.237765,2.409567,46.677897,0,1,0,0
2,41.0,15.886446,2.913410,150.177829,0,1,0,0
3,83.0,30.020028,6.922304,298.246340,0,1,0,0
4,15.0,8.437408,1.405998,56.594181,0,0,1,0
...,...,...,...,...,...,...,...,...
4567,26.0,4.472360,0.717090,94.685866,0,0,1,0
4568,71.0,20.610685,6.545573,249.101915,0,0,0,1
4569,44.0,19.800072,5.096192,163.631457,0,0,1,0
4570,71.0,17.534640,1.940873,253.610411,1,0,0,0
4571,42.0,15.966688,5.046548,148.202414,0,0,1,0

In [8]:
x=final_df.drop('Sales',axis=1)
y=final_df['Sales']
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=1,test_size=0.2)

In [9]:
y_train

1559    273.467668
2216     72.216447
4063    268.385836
388     290.199183
2279    172.731188
           ...
2921    194.243083
2789    162.969961
931     286.098165
4006    343.769533
261     239.732893
Name: Sales, Length: 3636, dtype: float64

In [10]:
lin_reg=LinearRegression()
lin_reg.fit(x_train,y_train)

LinearRegression()

In [11]:
with open("linear_regression_model_on_MarketingAndSalesData.pkl", 'wb') as f:
    model = pickle.dump(lin_reg,f)